### ISSUE TITLE
Error while building ../build.sh: 12: ../ghost.sh: Bad substitution

### ISSUE THREAD

**Issue by JustVic** [maxdev1/ghost#10]
While building getting this error:

/ghost/source/libuser$ ./build.sh all
./build.sh: 12: ../ghost.sh: Bad substitution

**Comment by maxdev1** [comment]
What shell did you use? Try it again with `/bin/bash`.

**Comment by JustVic** [comment]
I use debian and bash and nothing special.

vic@debian:~$ echo $SHELL
/bin/bash

**Comment by JustVic** [comment]
I try it with /bin/bash:

vic@debian:~/programming/ghost/source/libuser$ /bin/bash ./build.sh all
target: all
error: missing required tool 'changes'

And it seems work. But what tool is 'changes'? I don't find it.

**Comment by maxdev1** [comment]
This tool is in `/tools/changes`. Why are you building everything yourself? You should use the `toolchain.sh` in root. Take a look at this page:
https://github.com/maxdev1/ghost/blob/master/documentation/misc/compilation.adoc#toolchain-setup

**Comment by JustVic** [comment]
Thanks a lot. It's my mistake I had wrong version of automake. I installed right version and build toolchain  further... to the next error.

./toolchan.sh

...
Building GCC
    Configuration
    Building core
    Installing core
    Building target libgcc
Build failed


ghost-build.log:

In file included from ../../../gcc-4.9.1/libgcc/libgcc2.c:27:0:
../../../gcc-4.9.1/libgcc/../gcc/tsystem.h:87:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>

Sorry for my incompetence. I'll check what else I'm doing wrong.

**Comment by maxdev1** [comment]
@JustVic seems you found a way to fix this?

**Comment by munez07** [comment]
Hi, I am stuck to the same error
I use ubuntu 16.04
#bash toolchain.sh
...
Building GCC
    Configuration
    Building core
    Installing core
    Building target libgcc
Build failed

ghost-build.log:

In file included from ../../../gcc-4.9.1/libgcc/libgcc2.c:27:0:
../../../gcc-4.9.1/libgcc/../gcc/tsystem.h:87:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>

**Comment by JustVic** [comment]
I rebuild it on 32-bit only system and for building allways use "/bin/bash" (/bin/bash toolchain.sh)  to make sure that is run by bash.

**Comment by JustVic** [comment]
As I see stdio.h must to be copied when installing libc headers.  You may try to build libc without toolchain.sh. Maybe run /bin/bash build.sh in libc directory.

**Comment by munez07** [comment]
Thanks you! It solved my problem but I had another problem: ghost.h was not found so i executed build.sh install-header in libapi folder and after re-run toolchain.sh, gcc was successfully compiled.
Unfortunately, now I have another problem:
/bin/bash toolchain.sh
...
Building GCC
    Configuration
    Building core
    Installing core
    Building target libgcc
    Installing target libgcc
Building libc
Build failed

And into libc/ghost-build.log
build.sh: 12: ../ghost.sh: Bad substitution
build.sh: 12: ../ghost.sh: Bad substitution
Furthermore I found the same error in every ghost-build.log created by other script *.sh

**Comment by munez07** [comment]
I finally resolve replacing every "sh build.sh" into toolchain.sh with "/bin/bash build,sh"

**Comment by bluethefoxyt** [comment]
@maxdev1 can i compile in windows

**Comment by maxdev1** [comment]
@bluethefoxyt yes, you must use Cygwin. Look at the document about compiling in the documentation folder.
