### ISSUE TITLE
tetris application

### ISSUE THREAD

**Issue by JustVic** [maxdev1/ghost#13]
After I built all. I noticed tetris app in applications is not a real tetris. It does't make much sence to operating system development, but I tried to implement it. It turn out quite playable. I made gui contorls, because keyboard working a little strange and not always in time.
link to repository : https://github.com/JustVic/ghost_tetris

**Comment by MarcoCicognani** [comment]
Very good work JustVic, i'm the developer of a derived operating system from Ghost Kernel (https://github.com/MarcoCicognani/MeetiX-OS-Project). Would you like to write the "pong" game for this platform? I would also adapt it to my system by leaving it naturally in your name😉

**Comment by JustVic** [comment]
to MarcoCIcognani:Ok I can try. With GUI buttons I think it's not a problem. But with keyboard I don't understand yet, why keypress not always works.

**Comment by MarcoCicognani** [comment]
I know,  on my gui libs there Is a container util named ButtonList, It permit to create a collection  of buttons  managed with one object

**Comment by maxdev1** [comment]
Hey @JustVic,
nice work, good to see you managed to create something with Ghost. Did you have major issues building the system yourself or anything I could clarify better in the documentation?
I will also add your Tetris to the mainstream. If you want, you can also create a pull request to the repository that I can simply merge!
Thanks for your contributions :+1:

**Comment by maxdev1** [comment]
Hey @JustVic,
just found time to revise the code. It's very impressing that you found out how to use the APIs without much documentation! 😛 Thanks for your contribution. 👍  Your game was included in the OS. I also just fixed an issue that made the window server freeze often, might make it easier to keep developing on it. I'll try to get keyboard support for UI applications ASAP, so maybe you'd like to add it to Tetris then, too.
Greets!
