### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by speartaker** [maxdev1/ghost#15]
I did **_everything_** as suggested, without skipping anything crucial and got these messages:

- Many of these: `build.sh: 12: ../ghost.sh: Bad substitution`
- Terminal output: // only the important part, everything else is OK
Building GCC
    Configuration
Build failed
- `configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.`

My operating system:

- Linux Ubuntu 16.04

**Comment by speartaker** [comment]
Even if I download GMP, MPFR and MPC and place them manually it refuses to work, throwing:

- Building GCC
    Configuration
    Building core
Build failed
- `../../gcc-4.9.1/gcc/system.h:647:17: fatal error: gmp.h: No such file or directory`

**Comment by speartaker** [comment]
M4 was missing so I installed it, + installed GMP, MPFR and MPC.
GCC build keeps failing! // Building core part
- `The directory that should contain system headers does not exist:
  /ghost/sysroot/system/include`

**Comment by maxdev1** [comment]
Does the directory `/ghost/sysroot/system/include` exist? It is created when executing the `build.sh install-headers` task of libapi.

**Comment by speartaker** [comment]
Hey, thanks for replying.
It certainly does not exist. That is the problem I guess.
