### ISSUE TITLE
Please give some tips on making drivers for Ghost os

### ISSUE THREAD

**Issue by UtkrishtTech** [maxdev1/ghost#19]
Please tell me how can I write drivers for Ghost OS and in which languages can I write Drivers. Is it important to use c++ or I can use c or any other language also.

**Comment by maxdev1** [comment]
Drivers in Ghost are applications like all others, the only difference is that they must be started with a higher security level. Check the ps2driver for an implementation example.

You can write them in any language that calls kernel library functions in a way that complies with the System V ABI. You must have a cross-compiler for Ghost for your language of choice.

**Comment by UtkrishtTech** [comment]
Thank you sir, I am trying to make a graphical driver utility for Ghost OS that can be used by anyone to create drivers for their hardware and upload it in the ghost kernel database. The person will not need to program anything only he or she has to graphically select the configuration and test it.

**Comment by maxdev1** [comment]
Have you ever programmed a driver by yourself? The idea sounds a little utopic :-P

**Comment by UtkrishtTech** [comment]
Yes I have done it in both c and cpp
