### ISSUE TITLE
Booting Problem on Physical Machine

### ISSUE THREAD

**Issue by eilhanz** [maxdev1/ghost#21]
I'm wanted test your operating system on my physical computer. I'm flashed your demo ISO but when I'm booting the Ghost Kernel is freezed at boot logo & fully not functional.
There is an example photo:
![img_20190215_120356_1](https://user-images.githubusercontent.com/28977114/52846632-308dfb00-311b-11e9-8419-5c7e4c93c1a6.jpg)
Thank you.

**Comment by maxdev1** [comment]
Hi @eilhanz 
There is probably an issue with the VBE driver - unfortunately when pretty boot is enabled you don't see the error log. To solve it, you would have to change the `G_PRETTY_BOOT` (kernel/src-shared/build_config.hpp) and rebuild the kernel.
Greets

**Comment by eilhanz** [comment]
Thank you again. :)
