### ISSUE TITLE
How can I boot from ISO?

### ISSUE THREAD

**Issue by xiaokang00010** [maxdev1/ghost#25]
I'm try run it on VMware Fusion,but it didn't working
Is it need an filesystem on harddisk?

**Comment by maxdev1** [comment]
It doesn't need a filesystem, but there might be some compatibility issue in VMWare Fusion. No idea what it is though, you see anything in the log?

**Comment by EndermanPC** [comment]
it not work in Vbox too

**Comment by maxdev1** [comment]
Should be fixed with the recent changes where PIC is supported again. Check the latest ISO on the website
