### ISSUE TITLE
Cairo's Linking

### ISSUE THREAD

**Issue by MarcoCicognani** [maxdev1/ghost#3]
Hi, good morning.
I'm a little programmer and i have a problem...
On Linux Mint 18 Cinnamon (64 bit) i tried to build cairo library, first with your custom compiler, but the compiling fail.
i tried with standard g++/gcc (32 bit) and the compiling finish successfull, but linking with windows server don't work, errors (linking time)
 are hundreds, all of missing part of cairo library... O.o
i tried all roads, but nothing...help me, please

[err.txt](https://github.com/maxdev1/ghost/files/413356/err.txt)

**Comment by maxdev1** [comment]
Hello,

what are you trying to achieve? Compile cairo for your own OS?

Greets

2016-08-11 15:55 GMT+02:00 MarcoCicognani <notifications@github.com>:

**Comment by MarcoCicognani** [comment]
yes, i would like compile Cairo for your Ghost OS

2016-08-11 16:00 GMT+02:00 Max Schlüssel <notifications@github.com>:

**Comment by MarcoCicognani** [comment]
Solved, thanks for time, i've passed at cairo's make CC variable
/<my_path_to_ghost>/bin/i686-ghost-gcc and now linking work. thanks

2016-08-11 18:50 GMT+02:00 Marco Cicognani <marco.cicognani.2k@gmail.com>:

**Comment by lukaandjelkovic** [comment]
This shall be closed.

**Comment by maxdev1** [comment]
Ah very nice! Good job. It would be really nice once your done, if you could tell me whether you had any other problems when setting it up, so I can improve documentation.
