### ISSUE TITLE
Use Makefiles instead shell scripts

### ISSUE THREAD

**Issue by NikOverflow** [maxdev1/ghost#40]
Why do you use shell scripts when you can also use Makefiles? I think that Makefiles make things much easier. You can just make the rules so that it compiles correctly.

**Comment by maxdev1** [comment]
To be honest, I think the scripts actually make it much more maintainable and easier to control what to build when & influence it with commands.

Nevertheless, if you feel like it would make it easier, feel free to create a PR

**Comment by NikOverflow** [comment]
> To be honest, I think the scripts actually make it much more maintainable and easier to control what to build when & influence it with commands.
> 
> Nevertheless, if you feel like it would make it easier, feel free to create a PR

Do you have Discord? Maybe you could contact me as I have some questions and ideas. My name on Discord is nikoverflow
