### ISSUE TITLE
Issue on VMWare Workstation 12 Player - ghost-0.5.3

### ISSUE THREAD

**Issue by NunoLava1998** [maxdev1/ghost#7]
I am trying to run your Ghost OS 0.5.3 on VMWare WorkStation 12 Player, but it freezes at the "read README" shell.

Thank you for addressing this issue, if addressed.

**Comment by maxdev1** [comment]
This could have different causes, I'd need more information on your VM to find that out. It would also be an option to enable your serial port COM1 and let it write to a file - like this you can see the kernel log.
